/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Account */

#ifndef _Included_Account
#define _Included_Account
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Account
 * Method:    store
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Account_store__
  (JNIEnv *, jobject);

/*
 * Class:     Account
 * Method:    store
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Account_store__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
